In [1]:
import torch
from linalg_base import *


In [2]:
create_samples()[1]

(tensor([1., 2., 3.]),
 tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]))

In [ ]:
x = torch.tensor([1.0,2.0,3.0])
y = torch.tensor([4.0,5.0,6.0])

result = dot_product(x, y, backend='pytorch')


In [4]:
result.item()

32.0

In [5]:
import numpy as np

In [7]:
w1 = np.array([1,2,3])
w2 = np.array([4,5,6])
w3 = np.array([7,8,9])

x1, x2, x3 = 1, -2, 1

result = x1 * w1 + x2 * w2 + x3 * w3

In [8]:
result

array([0, 0, 0])

In [10]:
W = np.column_stack((w1, w2, w3))
det = np.linalg.det(W)
det

np.float64(0.0)

In [12]:
u = np.array([1.0, 0.0])
v = np.array([-0.5, np.sqrt(3) / 2])
w = np.array([-0.5, -np.sqrt(3) / 2])

dot_uv = np.dot(u, v)
dot_uw = np.dot(u, w)
dot_vw = np.dot(v, w)

dot_uv, dot_uw, dot_vw

(np.float64(-0.5), np.float64(-0.5), np.float64(-0.4999999999999999))

In [16]:
v = np.array([3.0, 4.0])
w = np.array([5.0, 12.0])

# method a:
alpha = np.arctan2(v[1], v[0])
beta = np.arctan2(w[1], w[0])
alpha, beta

(np.float64(0.9272952180016122), np.float64(1.176005207095135))

In [18]:
cos_alpha, sin_alpha = v[0] / np.linalg.norm(v), v[1] / np.linalg.norm(v)
cos_beta, sin_beta = w[0] / np.linalg.norm(w), w[1] / np.linalg.norm(w)

cos_theta_trig = cos_alpha * cos_beta + sin_alpha * sin_beta

# 3. Способ Б: Через скалярное произведение (как в векторизованном ML)
cos_theta_vector = np.dot(v, w) / (np.linalg.norm(v) * np.linalg.norm(w))
print(f"Cos(theta) через тригонометрию: {cos_theta_trig:.4f}")
print(f"Cos(theta) через векторную формулу: {cos_theta_vector:.4f}")
print(f"Результаты совпадают: {np.isclose(cos_theta_trig, cos_theta_vector)}")

Cos(theta) через тригонометрию: 0.9692
Cos(theta) через векторную формулу: 0.9692
Результаты совпадают: True
